#NOM : Makefile
#CLASSE : SYSG5 - Steganography Rapport
#OBJET : Rapport du projet de stéganographie - Formats bitmap et GIF
#HOWTO : make ; make clean
#AUTEUR : Foud Hind et Patti Philippe


rapport :
	@./goSlides	

clean : 
	rm *.aux *.log *.pdf *.ps *.toc *.fdb_latexmk *.fls
